.PHONY: krait_32 bagheera2 x86 clean

krait_32:
	cd krait && $(MAKE) $(MAKECMDGOALS)

bagheera2:
	cd bagheera2 && $(MAKE) $(MAKECMDGOALS)

x86:
	cd bagheera2 && $(MAKE) $(MAKECMDGOALS)

clean:
	rm -rf krait/out
	rm -rf bagheera2/out
