sonar.projectKey=nd_device_services
sonar.projectName=nd_device_services
sonar.projectVersion=1.0
sonar.sources= awsiot/nd_iot/inc,awsiot/nd_iot/src,nd-central/device/bagheera2/io/,nd-central/device/bagheera2/inc,nd-central/common/,circular_buffer/,uploader/,scheduler_manager/,ext_cam/,wifi_mgr/,installer_app/bagheera2/,svc/,speed/,service_mon/,time_sync/,diagnostic/,power_monitor/,apm/,nd-cam_recorder/,nd_shutdown/,nd_suspendresume/,fan_control/,nd_sam/src/,nd_bt/src/,gps/inc,gps/src
sonar.cfamily.build-wrapper-output=./
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarqube-enterprise.netradyne.info/
