/var/log/syslog {
        missingok
        notifempty
        daily
        create 0644 root root
        rotate 70
        size 5M
        dateext
        dateformat %Y%m%d:%s
        compress
        postrotate
            /bin/kill -HUP `cat /var/run/rsyslogd.pid 2> /dev/null` 2> /dev/null || true
        endscript
}
