/var/log/messages*
/var/log/debug*
/var/log/kern.*
/var/log/syslog {
        missingok
        notifempty
        daily
        create 0644 root root
        rotate 7
        size 50M
        maxsize 50M
        extension .log
        compress
        sharedscripts
        postrotate
        /bin/kill -HUP `cat /var/run/rsyslogd.pid 2> /dev/null` 2> /dev/null || true
        endscript
}
