#/*********************************************************************************
#*********************************************************************************/

cmake_minimum_required (VERSION 3.5)
project (nd_sam)

add_subdirectory (src/daemon)
add_subdirectory (src/console)
#add_subdirectory (src/test)
