#/*********************************************************************************
#*********************************************************************************/

cmake_minimum_required (VERSION 3.5)
project(nd_bt)

add_subdirectory (src/lib)
add_subdirectory (src/daemon)
add_subdirectory (src/cli)
# add_subdirectory (src/test)
