[ext_cam]
ch1_enabled=false             ; Flag to enable MDVR CH1 streaming
ch1_framerate=30              ; framerate for CH1
ch2_enabled=false             ; Flag to enable MDVR CH2 streaming
ch2_framerate=30              ; framerate for CH2
ch3_enabled=false             ; Flag to enable MDVR CH3 streaming
ch3_framerate=30              ; framerate for CH3
ch4_enabled=false             ; Flag to enable MDVR CH4 streaming
ch4_framerate=30              ; framerate for CH4

[ext_cam_audio]
ch1_audio_enabled = false     ; enable audio from CH1
ch2_audio_enabled = false     ; enable audio from CH2
ch3_audio_enabled = false     ; enable audio from CH3
ch4_audio_enabled = false     ; enable audio from CH4

[ext_cam_time]
time_zone=-800                ; time zone relative to GMT, IST: 530, PST: -700, EST: -400, CST: -500, AKST: -900, HST: -1000, MST: -600 etc
video_timestamp_enable=false  ; to enable or disable timestamps on videos

[ext_cam_settings]
retry_count_vod=3             ; max number of times we retry before sending vod failure to cloud for external cameras
sleep_retry=120               ; sleep between the vod retries for external cameras
max_pull_time=600             ; max time to wait for mdvr file pull if file not found even after retries
time_offset_millis = -2000    ; to offset video by few millisecs to get sync
file_empty_max_retry_count=30 ; max retry count when we receive empty files from visionpro
mdvr_firmware_upgrade=false    ; MDVR Firmware Upgrade Configuration
save_ext_cam_files_in_dhub = true; HUB Session Files will be saved in HUB itself if made true;
mdvr_health_check_duration = 1; time between check for mdvr healthstats
ext_cam_request_duration = 60; ext cam video request duration in seconds

[NightMode]
ir_mode = auto
max_lux = 60
min_lux = 40
; irled_off_hr should be between 00:00 AM and irled_on_hr
irled_on_hr = 16                   ; Turn on IRLED at 4pm local time - changed to adjust winter
irled_off_hr = 7                   ; Turn off IRLED at 7am local time
irled_on_intensity = 30            ; % of intensity level for IR LEDs, dafault 30 to avoid damage
analytics_control_ir_led = disable ; "enable" if we want analytics to control ir leds "disable" if not; default disable

