[sdcard]
sizeForCircularBuffer = 90                   ; %of SDcard allocated for circular buffer

[generic_queue]
thresholdGenericQueueLimit=70             ;Limit must be less then 120 as max queue size is 120.

[driverlogin]
enabled = true
login_speed = 15
login_time = 10                             ; time to maintain speed for login.
idle_speed = 0
idle_time = 300
bt_max_retry = 5                           ; BT scan retry count
bt_scan_retry_vp_enabled = 5               ; default scan retry count when visionpro is enabled
coexist_with_visionpro = true              ; by default this feature is set not to coexist with visionpro
curl_timeout = 60                           ; curl timeout for posting driver login
cloud_post_retry_interval = 10              ; Retry interval in minutes for cloud post

[driverlogin_fr]
enabled = true
idle_speed = 0
idle_time = 300

[privacy_mode]
enabled = true                           ; privacy feature is available or not. false case is also for for Amazon specific.
privacymode_led = true                   ;LED indication for privacy mode. If this is true, GPS status will not be notified via LED.
default_privacy = true             ;Default speed privacy status used by ndcentral until BTFV service enables/disables privacy
privacy_disable_speed = 5
privacy_disable_time = 3         
privacy_enable_speed = 0
privacy_enable_time = 180 
enable_ignition_based_privacy = true     ; if true ; enters to privacy on ign low comes out on ign high
button_long_press_for_privacy = false             ; button long press required for privacy ON
long_press_duration_ms = 5000             ; button long press duration
enable_inward_video_storage = true             ; if this is false don't save inward video even privacy is off.

[engine_idle]
enabled = false                             ;disabling engine idle by default from 0.4.6
engine_idle_enable_speed = 0                ;Speed below which you want to go to idle
engine_idle_enable_time = 36000             ;Time in secs after which you want to go to idle

[camera]
front=enable
back=disable
left=disable
right=disable
codecType = hevc
use_nvmm=true
nv_queue_size=25      ; NV buffer size for nvcamersrc gst element's queue-size property
is_drop_only = true
sync_files=true       ; whether to enable file sync feature or not
sync_freq_in_millisecs=1000 ; frequency at which video files should be synced (to be given in millisecs)
audio_enable=false      ; flag to enable audio recording
audio_encryption=true  ; flag to encrypt audio file
max_cam_crash_count=10 ; maximum crashes allowed for a camera in a single boot cycle. After this, disable the camera for the boot cycle
copy_hd_files=true
outward_nrt_bitrate=6000000
inward_nrt_bitrate=2000000
leftcam_nrt_bitrate=500000
rightcam_nrt_bitrate=500000

[package_inwardcam_streaming]
socket = ipc:///dev/shm/MSGQ/6357

[imu]
;gyro_scale: 0, 1, 2, 3
gyro_scale = 1
;gyro_dlpf_bw: 0, 1, 2, 3, 4, 5, 6, 7
gyro_dlpf_bw = 5
;accel_scale: 0, 1, 2, 3
accel_scale = 1
;accel_dlpf_bw: 1, 2, 3, 4, 5, 6
accel_dlpf_bw = 6
;sample_rate: 10,20,50,100,200,500
sample_rate = 20

[power]
cyclic_reboot_duration=960          ; cyclic reboot duration in mins; we cant disable this
crank_shutdown_duration=15          ; time in mins to keep the device on after crank voltage goes down
battery_health_monitor=on           ; consider battery voltage to shutdown
enable_lowpowermode=on              ; feature to wakeup during engine idle
max_lowpower_wakeups=56             ; number of time device wakesup in low power mode
lowpower_wakeup_cycle_duration=180  ; once in these mins device will wake up during engine off
lowpower_wakeup_duration=6          ; wakes up for this much duration during engine off
lowpower_wakeup_long_cycle_threshold=32  ; threshold after which device shall wakeup at every lowpower_wakeup_long_cycle_duration minutes till max_lowpower_wakeups is reached.
lowpower_wakeup_long_cycle_duration=1440          ; wakeup duration in minutes during engine off. Default 24 hours.
min_voltage_limit_V=10.01           ; int part of minimum working voltage (10 Volts)
max_voltage_limit_V=15.01           ; int part of maximum working voltage (15 Volts)
abnormal_voltage_wait_duration=3    ; wait for this secs and take call
allow_sdcard_reboot_freq=86400      ; reboot only once per day for SDcard RO calue in seconds(24*60*60secs)
fsck_lowpower_wakeup=2              ; low power wakeup number where fsck would be run. defaults to second low power wakeup
max_ignition=10                     ; max ignition per session for metadata
misc_wakeup_duration=3              ; wakeup duration in minutes for non RTC wakeup reasons

[home_ssid]
wifi_fallback=disable

[wifi]
wifi_fallback=enable
count=1
wifiname0=Netradyne-SSID
wifipassword0=12345678

[svc]
diskmon_enable = true
diskmon_poll = 180 #3 mins
config_recovery_enable = true
config_recovery_poll = 900 #15 mins

[speaker]
volume = 10 ; speaker volume while playing audio 0 to 10; 10 is maximum volume

[GPU_frequency_setting]
frequency_khz = 998400 ; supported 76800 153600 230400 307200 384000 460800 537600 614400 691200 768000 844800 921600 998400 (kHz)

[streaming]
enable_streaming = true
outwardcam_streaming = true
inwardcam_streaming = true
inertial_streaming = true
post_ignition_analytics_secs = 0    ;send frames to analytics these many seconds post ignition

[outwardcam_streaming]
socket = ipc:///dev/shm/MSGQ/6355
analytics_fps = 5
width = 640
height = 360
enable_crop = false
crop_top_left_x = -1
crop_top_left_y = -1
crop_top_right_x = -1
crop_top_right_y = -1
crop_bottom_left_x = -1
crop_bottom_left_y = -1
crop_bottom_right_x = -1
crop_bottom_right_y = -1

[inwardcam_streaming]
socket = ipc:///dev/shm/MSGQ/6356
analytics_fps = 5
width = 640
height = 360
enable_crop = false


[inertial_streaming]
socket = ipc:///dev/shm/MSGQ/6365
[gps_streaming]
gps_socket = ipc:///dev/shm/MSGQ/6370


[INSTALLER_APP]
static_ip = 10.42.0.1
static_port= 5000
socket_timeout=90
generic_cmd_feature=true

[process_mon]
error_report = true

[obd_service]
enabled= false

[Transcode]
enable=true                        ; true, 1 or false, 0. decides both inward and outward transcoding
num_hq_videos_max=120              ; number of videos to store in HQ
delay=10                           ; delay in seconds before the next transcode is taken up
enable_smart_transcode=true        ; if enabled, uses values from analytics to determine compression type
enable_inward_transcode=true       ; if enabled, transcodes inward videos. if enable = false, this value is ignored

[time_sync]
enabled=true                      ; Global control to disable full time sync feature
gps_time_sync_enable=true         ; Control to disable gps time sync alone. Global control should br true for this to take effect
network_time_sync_enable=true     ; Control to disable network time sync alone. Global control should br true for this to take effect

[device_store]
store_path="/home/ubuntu/.nddevice/latest/store.nds" ; Path to fetch store for operations.

[internal_buffer]
max_normal_sessions = 30 ; number of normal sessions to be stored
max_alert_sessions = 6   ; number of alert sessions to be stored
enable_alert_priority_after = 12 ; if internal buffer cannot store above this many sessions, alert sessions will be added as normal sessions
per_session_video_space_MB = 80 ; ( 45+15+4+4 + 8+4 ) // HQ(outward+inward+left+right) + LQ(outward+inward) 
use_backup_space_below_MB = 500 ; if ib limit goes below 500MB, it will use backup space up to a max of this value
safety_backup_space_MB = 400 ; space over and above svc backup space
svc_backup_space_MB = 1000 ; svc back up space
filling_limit_zero_below_MB = 300 ; filling limit is set to 0 when emmc_available (free space) falls below this amount

[J1939_update_rates]
speed=1000  ;all update rates are in ms
RPM=1000
Throttle_position=1000
Oil_pressure=30000
Coolant_Temperature=30000
BrakeSwitch=30000
Odometer=30000
Engine_Hour=30000
Fuel_used=30000
Steering_wheel_angle=30000
Brake_pedal_position=30000
Current_Gear=30000

[OBDII_update_rates]
speed=1000         ;all update rates are in ms
rpm=1000
Throttle_position=1000
Coolant_Temperature=30000
fuel_level=30000
Engine_On_time=30000
distence_since_code_cleared=30000
fuel_system_status=30000
MAF_air_flow_rate=30000
Absolute_Barometric_Pressure=30000
Ambient_air_temperature=30000
prop_param1 =30000
prop_param2 =30000
prop_param3 =30000
prop_param4 =30000
prop_param5 =30000
prop_param6 =30000
prop_param7 =30000
prop_param8 =30000
prop_param9 =30000
prop_param10 =30000

[list_of_prop_canid]
enabled=false
prop_param1 =0
prop_param2 =0
prop_param3 =0
prop_param4 =0
prop_param5 =0
prop_param6 =0
prop_param7 =0
prop_param8 =0
prop_param9 =0
prop_param10 =0


[aws_iot_publish]
enabled=false
publish_freq_in_secs=10  ; Value in secs

[log]
log_freq_bloating = 500
enable_non_critical = false
non_critical_log_retain_period = 30
enable_age_based_deletion = false
service_based_critical_log_filter = false

[vm]
enabled=true
dirty_writeback_centisecs=100          ; Post this time linux shall start writeback flush on dirty cache. 100 centisecond = 1 sec
dirty_expire_centisecs=100             ; Post this time linux starts fore flush on dirty cache.

[gps]
gps_fail_counter = 5                    ; in minutes, post this gps recover command is run

[uploader_settings]
conn_timeout_alert=90
max_timeout_alert=120
vod_timeout_hrs = 72

[upload_settings]
observation_frequency = 10 ; This value needs to be an integer and can be anything between 1 & 10

[live_streaming]
enabled=false
enc_type=2
fps=10
width=640
height=360
bitrate=512000
iframeinterval = 10
outward_stream_start_file=/home/ubuntu/autocam/audio/nd_debug2/live_streaming_outward_start.wav
outward_stream_end_file=/home/ubuntu/autocam/audio/nd_debug2/live_streaming_outward_end.wav
inward_stream_start_file=/home/ubuntu/autocam/audio/nd_debug2/live_streaming_inward_start.wav
inward_stream_end_file=/home/ubuntu/autocam/audio/nd_debug2/live_streaming_inward_end.wav
audio_notification=false

[diagnostic]
sdcard_diag_interval_time=60
sdcard_diag_start_time = 30
enable_all_time_sdcard_error_state_log=false

[hdmaps_mode]
metadata = false
enable = false
imu_data = false

[ublox]
enabled = false
led_indication = false
send_ubx_cfg_msgs = true
log_ubx_msgs = true
save_ubx_cfg = true
disable_nmea_msgs = true
enable_SBAS = false

[healthstats]
process_info_secs = 5 ;frequency of process info sampling
cpu_gpu_info_secs = 5 ;frequency of cpu gpu free info sampling
videohealthstats_secs = 600 ;frequency of uploading data to the cloud
healthstats_secs = 60 ;frequency of healthstats sampling
db_version = 2 ;DB version is 2
