// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: audio.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "audio.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace nd_audio {

namespace {

const ::google::protobuf::Descriptor* AudioData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AudioData_reflection_ = NULL;
const ::google::protobuf::Descriptor* SessionInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SessionInfo_reflection_ = NULL;
const ::google::protobuf::Descriptor* AudioMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AudioMessage_reflection_ = NULL;
struct AudioMessageOneofInstance {
  const ::nd_audio::AudioData* audio_data_;
  const ::nd_audio::SessionInfo* session_info_;
}* AudioMessage_default_oneof_instance_ = NULL;
const ::google::protobuf::Descriptor* AudioEvent_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AudioEvent_reflection_ = NULL;
const ::google::protobuf::Descriptor* AudioEvents_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AudioEvents_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_audio_2eproto() {
  protobuf_AddDesc_audio_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "audio.proto");
  GOOGLE_CHECK(file != NULL);
  AudioData_descriptor_ = file->message_type(0);
  static const int AudioData_offsets_[12] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, session_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, alert_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, frame_gen_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, issue_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, acceptable_latency_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, volume_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, audio_file_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, event_code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, uuid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, enabled_in_config_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, play_audio_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, reason_),
  };
  AudioData_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AudioData_descriptor_,
      AudioData::default_instance_,
      AudioData_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AudioData));
  SessionInfo_descriptor_ = file->message_type(1);
  static const int SessionInfo_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionInfo, session_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionInfo, frame_gen_time_),
  };
  SessionInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SessionInfo_descriptor_,
      SessionInfo::default_instance_,
      SessionInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SessionInfo));
  AudioMessage_descriptor_ = file->message_type(2);
  static const int AudioMessage_offsets_[3] = {
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(AudioMessage_default_oneof_instance_, audio_data_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(AudioMessage_default_oneof_instance_, session_info_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioMessage, inner_audio_message_),
  };
  AudioMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AudioMessage_descriptor_,
      AudioMessage::default_instance_,
      AudioMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioMessage, _unknown_fields_),
      -1,
      AudioMessage_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioMessage, _oneof_case_[0]),
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AudioMessage));
  AudioEvent_descriptor_ = file->message_type(3);
  static const int AudioEvent_offsets_[11] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvent, event_code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvent, uuid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvent, frame_timestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvent, alert_issue_timestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvent, playback_start_timestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvent, playback_end_timestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvent, playback_success_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvent, enabled_in_config_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvent, reason_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvent, latency_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvent, latency_threshold_),
  };
  AudioEvent_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AudioEvent_descriptor_,
      AudioEvent::default_instance_,
      AudioEvent_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvent, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvent, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AudioEvent));
  AudioEvents_descriptor_ = file->message_type(4);
  static const int AudioEvents_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvents, event_),
  };
  AudioEvents_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AudioEvents_descriptor_,
      AudioEvents::default_instance_,
      AudioEvents_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvents, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioEvents, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AudioEvents));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_audio_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AudioData_descriptor_, &AudioData::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SessionInfo_descriptor_, &SessionInfo::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AudioMessage_descriptor_, &AudioMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AudioEvent_descriptor_, &AudioEvent::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AudioEvents_descriptor_, &AudioEvents::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_audio_2eproto() {
  delete AudioData::default_instance_;
  delete AudioData_reflection_;
  delete SessionInfo::default_instance_;
  delete SessionInfo_reflection_;
  delete AudioMessage::default_instance_;
  delete AudioMessage_default_oneof_instance_;
  delete AudioMessage_reflection_;
  delete AudioEvent::default_instance_;
  delete AudioEvent_reflection_;
  delete AudioEvents::default_instance_;
  delete AudioEvents_reflection_;
}

void protobuf_AddDesc_audio_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013audio.proto\022\010nd_audio\"\207\002\n\tAudioData\022\024\n"
    "\014session_name\030\001 \001(\t\022\022\n\nalert_type\030\002 \001(\t\022"
    "\026\n\016frame_gen_time\030\003 \001(\004\022\022\n\nissue_time\030\004 "
    "\001(\004\022\032\n\022acceptable_latency\030\005 \001(\004\022\016\n\006volum"
    "e\030\006 \001(\005\022\027\n\017audio_file_name\030\007 \001(\t\022\022\n\neven"
    "t_code\030\010 \001(\t\022\014\n\004uuid\030\t \001(\t\022\031\n\021enabled_in"
    "_config\030\n \001(\010\022\022\n\nplay_audio\030\013 \001(\010\022\016\n\006rea"
    "son\030\014 \001(\t\";\n\013SessionInfo\022\024\n\014session_name"
    "\030\001 \001(\t\022\026\n\016frame_gen_time\030\002 \001(\004\"\177\n\014AudioM"
    "essage\022)\n\naudio_data\030\001 \001(\0132\023.nd_audio.Au"
    "dioDataH\000\022-\n\014session_info\030\002 \001(\0132\025.nd_aud"
    "io.SessionInfoH\000B\025\n\023inner_audio_message\""
    "\231\002\n\nAudioEvent\022\022\n\nevent_code\030\001 \001(\t\022\014\n\004uu"
    "id\030\002 \001(\t\022\027\n\017frame_timestamp\030\003 \001(\004\022\035\n\025ale"
    "rt_issue_timestamp\030\004 \001(\004\022 \n\030playback_sta"
    "rt_timestamp\030\005 \001(\004\022\036\n\026playback_end_times"
    "tamp\030\006 \001(\004\022\030\n\020playback_success\030\007 \001(\010\022\031\n\021"
    "enabled_in_config\030\010 \001(\010\022\016\n\006reason\030\t \001(\t\022"
    "\017\n\007latency\030\n \001(\004\022\031\n\021latency_threshold\030\013 "
    "\001(\004\"2\n\013AudioEvents\022#\n\005event\030\001 \003(\0132\024.nd_a"
    "udio.AudioEvent", 815);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "audio.proto", &protobuf_RegisterTypes);
  AudioData::default_instance_ = new AudioData();
  SessionInfo::default_instance_ = new SessionInfo();
  AudioMessage::default_instance_ = new AudioMessage();
  AudioMessage_default_oneof_instance_ = new AudioMessageOneofInstance;
  AudioEvent::default_instance_ = new AudioEvent();
  AudioEvents::default_instance_ = new AudioEvents();
  AudioData::default_instance_->InitAsDefaultInstance();
  SessionInfo::default_instance_->InitAsDefaultInstance();
  AudioMessage::default_instance_->InitAsDefaultInstance();
  AudioEvent::default_instance_->InitAsDefaultInstance();
  AudioEvents::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_audio_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_audio_2eproto {
  StaticDescriptorInitializer_audio_2eproto() {
    protobuf_AddDesc_audio_2eproto();
  }
} static_descriptor_initializer_audio_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int AudioData::kSessionNameFieldNumber;
const int AudioData::kAlertTypeFieldNumber;
const int AudioData::kFrameGenTimeFieldNumber;
const int AudioData::kIssueTimeFieldNumber;
const int AudioData::kAcceptableLatencyFieldNumber;
const int AudioData::kVolumeFieldNumber;
const int AudioData::kAudioFileNameFieldNumber;
const int AudioData::kEventCodeFieldNumber;
const int AudioData::kUuidFieldNumber;
const int AudioData::kEnabledInConfigFieldNumber;
const int AudioData::kPlayAudioFieldNumber;
const int AudioData::kReasonFieldNumber;
#endif  // !_MSC_VER

AudioData::AudioData()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:nd_audio.AudioData)
}

void AudioData::InitAsDefaultInstance() {
}

AudioData::AudioData(const AudioData& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:nd_audio.AudioData)
}

void AudioData::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  session_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  alert_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  frame_gen_time_ = GOOGLE_ULONGLONG(0);
  issue_time_ = GOOGLE_ULONGLONG(0);
  acceptable_latency_ = GOOGLE_ULONGLONG(0);
  volume_ = 0;
  audio_file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  event_code_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uuid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  enabled_in_config_ = false;
  play_audio_ = false;
  reason_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AudioData::~AudioData() {
  // @@protoc_insertion_point(destructor:nd_audio.AudioData)
  SharedDtor();
}

void AudioData::SharedDtor() {
  if (session_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete session_name_;
  }
  if (alert_type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete alert_type_;
  }
  if (audio_file_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete audio_file_name_;
  }
  if (event_code_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete event_code_;
  }
  if (uuid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete uuid_;
  }
  if (reason_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete reason_;
  }
  if (this != default_instance_) {
  }
}

void AudioData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AudioData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AudioData_descriptor_;
}

const AudioData& AudioData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_audio_2eproto();
  return *default_instance_;
}

AudioData* AudioData::default_instance_ = NULL;

AudioData* AudioData::New() const {
  return new AudioData;
}

void AudioData::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<AudioData*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 255) {
    ZR_(frame_gen_time_, acceptable_latency_);
    if (has_session_name()) {
      if (session_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        session_name_->clear();
      }
    }
    if (has_alert_type()) {
      if (alert_type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        alert_type_->clear();
      }
    }
    volume_ = 0;
    if (has_audio_file_name()) {
      if (audio_file_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        audio_file_name_->clear();
      }
    }
    if (has_event_code()) {
      if (event_code_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        event_code_->clear();
      }
    }
  }
  if (_has_bits_[8 / 32] & 3840) {
    ZR_(enabled_in_config_, play_audio_);
    if (has_uuid()) {
      if (uuid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        uuid_->clear();
      }
    }
    if (has_reason()) {
      if (reason_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        reason_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AudioData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:nd_audio.AudioData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string session_name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_session_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->session_name().data(), this->session_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "session_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_alert_type;
        break;
      }

      // optional string alert_type = 2;
      case 2: {
        if (tag == 18) {
         parse_alert_type:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_alert_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->alert_type().data(), this->alert_type().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "alert_type");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_frame_gen_time;
        break;
      }

      // optional uint64 frame_gen_time = 3;
      case 3: {
        if (tag == 24) {
         parse_frame_gen_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &frame_gen_time_)));
          set_has_frame_gen_time();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_issue_time;
        break;
      }

      // optional uint64 issue_time = 4;
      case 4: {
        if (tag == 32) {
         parse_issue_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &issue_time_)));
          set_has_issue_time();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_acceptable_latency;
        break;
      }

      // optional uint64 acceptable_latency = 5;
      case 5: {
        if (tag == 40) {
         parse_acceptable_latency:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &acceptable_latency_)));
          set_has_acceptable_latency();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_volume;
        break;
      }

      // optional int32 volume = 6;
      case 6: {
        if (tag == 48) {
         parse_volume:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &volume_)));
          set_has_volume();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_audio_file_name;
        break;
      }

      // optional string audio_file_name = 7;
      case 7: {
        if (tag == 58) {
         parse_audio_file_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_audio_file_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->audio_file_name().data(), this->audio_file_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "audio_file_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_event_code;
        break;
      }

      // optional string event_code = 8;
      case 8: {
        if (tag == 66) {
         parse_event_code:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_event_code()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->event_code().data(), this->event_code().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "event_code");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_uuid;
        break;
      }

      // optional string uuid = 9;
      case 9: {
        if (tag == 74) {
         parse_uuid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_uuid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->uuid().data(), this->uuid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "uuid");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(80)) goto parse_enabled_in_config;
        break;
      }

      // optional bool enabled_in_config = 10;
      case 10: {
        if (tag == 80) {
         parse_enabled_in_config:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &enabled_in_config_)));
          set_has_enabled_in_config();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(88)) goto parse_play_audio;
        break;
      }

      // optional bool play_audio = 11;
      case 11: {
        if (tag == 88) {
         parse_play_audio:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &play_audio_)));
          set_has_play_audio();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(98)) goto parse_reason;
        break;
      }

      // optional string reason = 12;
      case 12: {
        if (tag == 98) {
         parse_reason:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reason()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->reason().data(), this->reason().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "reason");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:nd_audio.AudioData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:nd_audio.AudioData)
  return false;
#undef DO_
}

void AudioData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:nd_audio.AudioData)
  // optional string session_name = 1;
  if (has_session_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->session_name().data(), this->session_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "session_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->session_name(), output);
  }

  // optional string alert_type = 2;
  if (has_alert_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->alert_type().data(), this->alert_type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "alert_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->alert_type(), output);
  }

  // optional uint64 frame_gen_time = 3;
  if (has_frame_gen_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->frame_gen_time(), output);
  }

  // optional uint64 issue_time = 4;
  if (has_issue_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(4, this->issue_time(), output);
  }

  // optional uint64 acceptable_latency = 5;
  if (has_acceptable_latency()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(5, this->acceptable_latency(), output);
  }

  // optional int32 volume = 6;
  if (has_volume()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->volume(), output);
  }

  // optional string audio_file_name = 7;
  if (has_audio_file_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->audio_file_name().data(), this->audio_file_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "audio_file_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->audio_file_name(), output);
  }

  // optional string event_code = 8;
  if (has_event_code()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->event_code().data(), this->event_code().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "event_code");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->event_code(), output);
  }

  // optional string uuid = 9;
  if (has_uuid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->uuid().data(), this->uuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "uuid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->uuid(), output);
  }

  // optional bool enabled_in_config = 10;
  if (has_enabled_in_config()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(10, this->enabled_in_config(), output);
  }

  // optional bool play_audio = 11;
  if (has_play_audio()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(11, this->play_audio(), output);
  }

  // optional string reason = 12;
  if (has_reason()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->reason().data(), this->reason().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "reason");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      12, this->reason(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:nd_audio.AudioData)
}

::google::protobuf::uint8* AudioData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:nd_audio.AudioData)
  // optional string session_name = 1;
  if (has_session_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->session_name().data(), this->session_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "session_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->session_name(), target);
  }

  // optional string alert_type = 2;
  if (has_alert_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->alert_type().data(), this->alert_type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "alert_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->alert_type(), target);
  }

  // optional uint64 frame_gen_time = 3;
  if (has_frame_gen_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->frame_gen_time(), target);
  }

  // optional uint64 issue_time = 4;
  if (has_issue_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(4, this->issue_time(), target);
  }

  // optional uint64 acceptable_latency = 5;
  if (has_acceptable_latency()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(5, this->acceptable_latency(), target);
  }

  // optional int32 volume = 6;
  if (has_volume()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->volume(), target);
  }

  // optional string audio_file_name = 7;
  if (has_audio_file_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->audio_file_name().data(), this->audio_file_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "audio_file_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->audio_file_name(), target);
  }

  // optional string event_code = 8;
  if (has_event_code()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->event_code().data(), this->event_code().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "event_code");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->event_code(), target);
  }

  // optional string uuid = 9;
  if (has_uuid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->uuid().data(), this->uuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "uuid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->uuid(), target);
  }

  // optional bool enabled_in_config = 10;
  if (has_enabled_in_config()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(10, this->enabled_in_config(), target);
  }

  // optional bool play_audio = 11;
  if (has_play_audio()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(11, this->play_audio(), target);
  }

  // optional string reason = 12;
  if (has_reason()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->reason().data(), this->reason().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "reason");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        12, this->reason(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nd_audio.AudioData)
  return target;
}

int AudioData::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string session_name = 1;
    if (has_session_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->session_name());
    }

    // optional string alert_type = 2;
    if (has_alert_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->alert_type());
    }

    // optional uint64 frame_gen_time = 3;
    if (has_frame_gen_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->frame_gen_time());
    }

    // optional uint64 issue_time = 4;
    if (has_issue_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->issue_time());
    }

    // optional uint64 acceptable_latency = 5;
    if (has_acceptable_latency()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->acceptable_latency());
    }

    // optional int32 volume = 6;
    if (has_volume()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->volume());
    }

    // optional string audio_file_name = 7;
    if (has_audio_file_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->audio_file_name());
    }

    // optional string event_code = 8;
    if (has_event_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->event_code());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional string uuid = 9;
    if (has_uuid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->uuid());
    }

    // optional bool enabled_in_config = 10;
    if (has_enabled_in_config()) {
      total_size += 1 + 1;
    }

    // optional bool play_audio = 11;
    if (has_play_audio()) {
      total_size += 1 + 1;
    }

    // optional string reason = 12;
    if (has_reason()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->reason());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AudioData::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AudioData* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AudioData*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AudioData::MergeFrom(const AudioData& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_session_name()) {
      set_session_name(from.session_name());
    }
    if (from.has_alert_type()) {
      set_alert_type(from.alert_type());
    }
    if (from.has_frame_gen_time()) {
      set_frame_gen_time(from.frame_gen_time());
    }
    if (from.has_issue_time()) {
      set_issue_time(from.issue_time());
    }
    if (from.has_acceptable_latency()) {
      set_acceptable_latency(from.acceptable_latency());
    }
    if (from.has_volume()) {
      set_volume(from.volume());
    }
    if (from.has_audio_file_name()) {
      set_audio_file_name(from.audio_file_name());
    }
    if (from.has_event_code()) {
      set_event_code(from.event_code());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_uuid()) {
      set_uuid(from.uuid());
    }
    if (from.has_enabled_in_config()) {
      set_enabled_in_config(from.enabled_in_config());
    }
    if (from.has_play_audio()) {
      set_play_audio(from.play_audio());
    }
    if (from.has_reason()) {
      set_reason(from.reason());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AudioData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AudioData::CopyFrom(const AudioData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AudioData::IsInitialized() const {

  return true;
}

void AudioData::Swap(AudioData* other) {
  if (other != this) {
    std::swap(session_name_, other->session_name_);
    std::swap(alert_type_, other->alert_type_);
    std::swap(frame_gen_time_, other->frame_gen_time_);
    std::swap(issue_time_, other->issue_time_);
    std::swap(acceptable_latency_, other->acceptable_latency_);
    std::swap(volume_, other->volume_);
    std::swap(audio_file_name_, other->audio_file_name_);
    std::swap(event_code_, other->event_code_);
    std::swap(uuid_, other->uuid_);
    std::swap(enabled_in_config_, other->enabled_in_config_);
    std::swap(play_audio_, other->play_audio_);
    std::swap(reason_, other->reason_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AudioData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AudioData_descriptor_;
  metadata.reflection = AudioData_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int SessionInfo::kSessionNameFieldNumber;
const int SessionInfo::kFrameGenTimeFieldNumber;
#endif  // !_MSC_VER

SessionInfo::SessionInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:nd_audio.SessionInfo)
}

void SessionInfo::InitAsDefaultInstance() {
}

SessionInfo::SessionInfo(const SessionInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:nd_audio.SessionInfo)
}

void SessionInfo::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  session_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  frame_gen_time_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SessionInfo::~SessionInfo() {
  // @@protoc_insertion_point(destructor:nd_audio.SessionInfo)
  SharedDtor();
}

void SessionInfo::SharedDtor() {
  if (session_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete session_name_;
  }
  if (this != default_instance_) {
  }
}

void SessionInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SessionInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SessionInfo_descriptor_;
}

const SessionInfo& SessionInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_audio_2eproto();
  return *default_instance_;
}

SessionInfo* SessionInfo::default_instance_ = NULL;

SessionInfo* SessionInfo::New() const {
  return new SessionInfo;
}

void SessionInfo::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_session_name()) {
      if (session_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        session_name_->clear();
      }
    }
    frame_gen_time_ = GOOGLE_ULONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SessionInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:nd_audio.SessionInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string session_name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_session_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->session_name().data(), this->session_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "session_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_frame_gen_time;
        break;
      }

      // optional uint64 frame_gen_time = 2;
      case 2: {
        if (tag == 16) {
         parse_frame_gen_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &frame_gen_time_)));
          set_has_frame_gen_time();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:nd_audio.SessionInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:nd_audio.SessionInfo)
  return false;
#undef DO_
}

void SessionInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:nd_audio.SessionInfo)
  // optional string session_name = 1;
  if (has_session_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->session_name().data(), this->session_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "session_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->session_name(), output);
  }

  // optional uint64 frame_gen_time = 2;
  if (has_frame_gen_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->frame_gen_time(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:nd_audio.SessionInfo)
}

::google::protobuf::uint8* SessionInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:nd_audio.SessionInfo)
  // optional string session_name = 1;
  if (has_session_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->session_name().data(), this->session_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "session_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->session_name(), target);
  }

  // optional uint64 frame_gen_time = 2;
  if (has_frame_gen_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->frame_gen_time(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nd_audio.SessionInfo)
  return target;
}

int SessionInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string session_name = 1;
    if (has_session_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->session_name());
    }

    // optional uint64 frame_gen_time = 2;
    if (has_frame_gen_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->frame_gen_time());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SessionInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SessionInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SessionInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SessionInfo::MergeFrom(const SessionInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_session_name()) {
      set_session_name(from.session_name());
    }
    if (from.has_frame_gen_time()) {
      set_frame_gen_time(from.frame_gen_time());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SessionInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SessionInfo::CopyFrom(const SessionInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SessionInfo::IsInitialized() const {

  return true;
}

void SessionInfo::Swap(SessionInfo* other) {
  if (other != this) {
    std::swap(session_name_, other->session_name_);
    std::swap(frame_gen_time_, other->frame_gen_time_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SessionInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SessionInfo_descriptor_;
  metadata.reflection = SessionInfo_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int AudioMessage::kAudioDataFieldNumber;
const int AudioMessage::kSessionInfoFieldNumber;
#endif  // !_MSC_VER

AudioMessage::AudioMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:nd_audio.AudioMessage)
}

void AudioMessage::InitAsDefaultInstance() {
  AudioMessage_default_oneof_instance_->audio_data_ = const_cast< ::nd_audio::AudioData*>(&::nd_audio::AudioData::default_instance());
  AudioMessage_default_oneof_instance_->session_info_ = const_cast< ::nd_audio::SessionInfo*>(&::nd_audio::SessionInfo::default_instance());
}

AudioMessage::AudioMessage(const AudioMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:nd_audio.AudioMessage)
}

void AudioMessage::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  clear_has_inner_audio_message();
}

AudioMessage::~AudioMessage() {
  // @@protoc_insertion_point(destructor:nd_audio.AudioMessage)
  SharedDtor();
}

void AudioMessage::SharedDtor() {
  if (has_inner_audio_message()) {
    clear_inner_audio_message();
  }
  if (this != default_instance_) {
  }
}

void AudioMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AudioMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AudioMessage_descriptor_;
}

const AudioMessage& AudioMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_audio_2eproto();
  return *default_instance_;
}

AudioMessage* AudioMessage::default_instance_ = NULL;

AudioMessage* AudioMessage::New() const {
  return new AudioMessage;
}

void AudioMessage::clear_inner_audio_message() {
  switch(inner_audio_message_case()) {
    case kAudioData: {
      delete inner_audio_message_.audio_data_;
      break;
    }
    case kSessionInfo: {
      delete inner_audio_message_.session_info_;
      break;
    }
    case INNER_AUDIO_MESSAGE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = INNER_AUDIO_MESSAGE_NOT_SET;
}


void AudioMessage::Clear() {
  clear_inner_audio_message();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AudioMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:nd_audio.AudioMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .nd_audio.AudioData audio_data = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_audio_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_session_info;
        break;
      }

      // optional .nd_audio.SessionInfo session_info = 2;
      case 2: {
        if (tag == 18) {
         parse_session_info:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_session_info()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:nd_audio.AudioMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:nd_audio.AudioMessage)
  return false;
#undef DO_
}

void AudioMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:nd_audio.AudioMessage)
  // optional .nd_audio.AudioData audio_data = 1;
  if (has_audio_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->audio_data(), output);
  }

  // optional .nd_audio.SessionInfo session_info = 2;
  if (has_session_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->session_info(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:nd_audio.AudioMessage)
}

::google::protobuf::uint8* AudioMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:nd_audio.AudioMessage)
  // optional .nd_audio.AudioData audio_data = 1;
  if (has_audio_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->audio_data(), target);
  }

  // optional .nd_audio.SessionInfo session_info = 2;
  if (has_session_info()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->session_info(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nd_audio.AudioMessage)
  return target;
}

int AudioMessage::ByteSize() const {
  int total_size = 0;

  switch (inner_audio_message_case()) {
    // optional .nd_audio.AudioData audio_data = 1;
    case kAudioData: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->audio_data());
      break;
    }
    // optional .nd_audio.SessionInfo session_info = 2;
    case kSessionInfo: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->session_info());
      break;
    }
    case INNER_AUDIO_MESSAGE_NOT_SET: {
      break;
    }
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AudioMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AudioMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AudioMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AudioMessage::MergeFrom(const AudioMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  switch (from.inner_audio_message_case()) {
    case kAudioData: {
      mutable_audio_data()->::nd_audio::AudioData::MergeFrom(from.audio_data());
      break;
    }
    case kSessionInfo: {
      mutable_session_info()->::nd_audio::SessionInfo::MergeFrom(from.session_info());
      break;
    }
    case INNER_AUDIO_MESSAGE_NOT_SET: {
      break;
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AudioMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AudioMessage::CopyFrom(const AudioMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AudioMessage::IsInitialized() const {

  return true;
}

void AudioMessage::Swap(AudioMessage* other) {
  if (other != this) {
    std::swap(inner_audio_message_, other->inner_audio_message_);
    std::swap(_oneof_case_[0], other->_oneof_case_[0]);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AudioMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AudioMessage_descriptor_;
  metadata.reflection = AudioMessage_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int AudioEvent::kEventCodeFieldNumber;
const int AudioEvent::kUuidFieldNumber;
const int AudioEvent::kFrameTimestampFieldNumber;
const int AudioEvent::kAlertIssueTimestampFieldNumber;
const int AudioEvent::kPlaybackStartTimestampFieldNumber;
const int AudioEvent::kPlaybackEndTimestampFieldNumber;
const int AudioEvent::kPlaybackSuccessFieldNumber;
const int AudioEvent::kEnabledInConfigFieldNumber;
const int AudioEvent::kReasonFieldNumber;
const int AudioEvent::kLatencyFieldNumber;
const int AudioEvent::kLatencyThresholdFieldNumber;
#endif  // !_MSC_VER

AudioEvent::AudioEvent()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:nd_audio.AudioEvent)
}

void AudioEvent::InitAsDefaultInstance() {
}

AudioEvent::AudioEvent(const AudioEvent& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:nd_audio.AudioEvent)
}

void AudioEvent::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  event_code_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uuid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  frame_timestamp_ = GOOGLE_ULONGLONG(0);
  alert_issue_timestamp_ = GOOGLE_ULONGLONG(0);
  playback_start_timestamp_ = GOOGLE_ULONGLONG(0);
  playback_end_timestamp_ = GOOGLE_ULONGLONG(0);
  playback_success_ = false;
  enabled_in_config_ = false;
  reason_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  latency_ = GOOGLE_ULONGLONG(0);
  latency_threshold_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AudioEvent::~AudioEvent() {
  // @@protoc_insertion_point(destructor:nd_audio.AudioEvent)
  SharedDtor();
}

void AudioEvent::SharedDtor() {
  if (event_code_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete event_code_;
  }
  if (uuid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete uuid_;
  }
  if (reason_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete reason_;
  }
  if (this != default_instance_) {
  }
}

void AudioEvent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AudioEvent::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AudioEvent_descriptor_;
}

const AudioEvent& AudioEvent::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_audio_2eproto();
  return *default_instance_;
}

AudioEvent* AudioEvent::default_instance_ = NULL;

AudioEvent* AudioEvent::New() const {
  return new AudioEvent;
}

void AudioEvent::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<AudioEvent*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 255) {
    ZR_(frame_timestamp_, playback_end_timestamp_);
    ZR_(playback_success_, enabled_in_config_);
    if (has_event_code()) {
      if (event_code_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        event_code_->clear();
      }
    }
    if (has_uuid()) {
      if (uuid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        uuid_->clear();
      }
    }
  }
  if (_has_bits_[8 / 32] & 1792) {
    ZR_(latency_, latency_threshold_);
    if (has_reason()) {
      if (reason_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        reason_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AudioEvent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:nd_audio.AudioEvent)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string event_code = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_event_code()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->event_code().data(), this->event_code().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "event_code");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_uuid;
        break;
      }

      // optional string uuid = 2;
      case 2: {
        if (tag == 18) {
         parse_uuid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_uuid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->uuid().data(), this->uuid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "uuid");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_frame_timestamp;
        break;
      }

      // optional uint64 frame_timestamp = 3;
      case 3: {
        if (tag == 24) {
         parse_frame_timestamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &frame_timestamp_)));
          set_has_frame_timestamp();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_alert_issue_timestamp;
        break;
      }

      // optional uint64 alert_issue_timestamp = 4;
      case 4: {
        if (tag == 32) {
         parse_alert_issue_timestamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &alert_issue_timestamp_)));
          set_has_alert_issue_timestamp();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_playback_start_timestamp;
        break;
      }

      // optional uint64 playback_start_timestamp = 5;
      case 5: {
        if (tag == 40) {
         parse_playback_start_timestamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &playback_start_timestamp_)));
          set_has_playback_start_timestamp();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_playback_end_timestamp;
        break;
      }

      // optional uint64 playback_end_timestamp = 6;
      case 6: {
        if (tag == 48) {
         parse_playback_end_timestamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &playback_end_timestamp_)));
          set_has_playback_end_timestamp();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_playback_success;
        break;
      }

      // optional bool playback_success = 7;
      case 7: {
        if (tag == 56) {
         parse_playback_success:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &playback_success_)));
          set_has_playback_success();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_enabled_in_config;
        break;
      }

      // optional bool enabled_in_config = 8;
      case 8: {
        if (tag == 64) {
         parse_enabled_in_config:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &enabled_in_config_)));
          set_has_enabled_in_config();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_reason;
        break;
      }

      // optional string reason = 9;
      case 9: {
        if (tag == 74) {
         parse_reason:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reason()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->reason().data(), this->reason().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "reason");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(80)) goto parse_latency;
        break;
      }

      // optional uint64 latency = 10;
      case 10: {
        if (tag == 80) {
         parse_latency:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &latency_)));
          set_has_latency();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(88)) goto parse_latency_threshold;
        break;
      }

      // optional uint64 latency_threshold = 11;
      case 11: {
        if (tag == 88) {
         parse_latency_threshold:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &latency_threshold_)));
          set_has_latency_threshold();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:nd_audio.AudioEvent)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:nd_audio.AudioEvent)
  return false;
#undef DO_
}

void AudioEvent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:nd_audio.AudioEvent)
  // optional string event_code = 1;
  if (has_event_code()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->event_code().data(), this->event_code().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "event_code");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->event_code(), output);
  }

  // optional string uuid = 2;
  if (has_uuid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->uuid().data(), this->uuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "uuid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->uuid(), output);
  }

  // optional uint64 frame_timestamp = 3;
  if (has_frame_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->frame_timestamp(), output);
  }

  // optional uint64 alert_issue_timestamp = 4;
  if (has_alert_issue_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(4, this->alert_issue_timestamp(), output);
  }

  // optional uint64 playback_start_timestamp = 5;
  if (has_playback_start_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(5, this->playback_start_timestamp(), output);
  }

  // optional uint64 playback_end_timestamp = 6;
  if (has_playback_end_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(6, this->playback_end_timestamp(), output);
  }

  // optional bool playback_success = 7;
  if (has_playback_success()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->playback_success(), output);
  }

  // optional bool enabled_in_config = 8;
  if (has_enabled_in_config()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->enabled_in_config(), output);
  }

  // optional string reason = 9;
  if (has_reason()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->reason().data(), this->reason().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "reason");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->reason(), output);
  }

  // optional uint64 latency = 10;
  if (has_latency()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(10, this->latency(), output);
  }

  // optional uint64 latency_threshold = 11;
  if (has_latency_threshold()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(11, this->latency_threshold(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:nd_audio.AudioEvent)
}

::google::protobuf::uint8* AudioEvent::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:nd_audio.AudioEvent)
  // optional string event_code = 1;
  if (has_event_code()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->event_code().data(), this->event_code().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "event_code");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->event_code(), target);
  }

  // optional string uuid = 2;
  if (has_uuid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->uuid().data(), this->uuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "uuid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->uuid(), target);
  }

  // optional uint64 frame_timestamp = 3;
  if (has_frame_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->frame_timestamp(), target);
  }

  // optional uint64 alert_issue_timestamp = 4;
  if (has_alert_issue_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(4, this->alert_issue_timestamp(), target);
  }

  // optional uint64 playback_start_timestamp = 5;
  if (has_playback_start_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(5, this->playback_start_timestamp(), target);
  }

  // optional uint64 playback_end_timestamp = 6;
  if (has_playback_end_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(6, this->playback_end_timestamp(), target);
  }

  // optional bool playback_success = 7;
  if (has_playback_success()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->playback_success(), target);
  }

  // optional bool enabled_in_config = 8;
  if (has_enabled_in_config()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->enabled_in_config(), target);
  }

  // optional string reason = 9;
  if (has_reason()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->reason().data(), this->reason().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "reason");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->reason(), target);
  }

  // optional uint64 latency = 10;
  if (has_latency()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(10, this->latency(), target);
  }

  // optional uint64 latency_threshold = 11;
  if (has_latency_threshold()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(11, this->latency_threshold(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nd_audio.AudioEvent)
  return target;
}

int AudioEvent::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string event_code = 1;
    if (has_event_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->event_code());
    }

    // optional string uuid = 2;
    if (has_uuid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->uuid());
    }

    // optional uint64 frame_timestamp = 3;
    if (has_frame_timestamp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->frame_timestamp());
    }

    // optional uint64 alert_issue_timestamp = 4;
    if (has_alert_issue_timestamp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->alert_issue_timestamp());
    }

    // optional uint64 playback_start_timestamp = 5;
    if (has_playback_start_timestamp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->playback_start_timestamp());
    }

    // optional uint64 playback_end_timestamp = 6;
    if (has_playback_end_timestamp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->playback_end_timestamp());
    }

    // optional bool playback_success = 7;
    if (has_playback_success()) {
      total_size += 1 + 1;
    }

    // optional bool enabled_in_config = 8;
    if (has_enabled_in_config()) {
      total_size += 1 + 1;
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional string reason = 9;
    if (has_reason()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->reason());
    }

    // optional uint64 latency = 10;
    if (has_latency()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->latency());
    }

    // optional uint64 latency_threshold = 11;
    if (has_latency_threshold()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->latency_threshold());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AudioEvent::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AudioEvent* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AudioEvent*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AudioEvent::MergeFrom(const AudioEvent& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_event_code()) {
      set_event_code(from.event_code());
    }
    if (from.has_uuid()) {
      set_uuid(from.uuid());
    }
    if (from.has_frame_timestamp()) {
      set_frame_timestamp(from.frame_timestamp());
    }
    if (from.has_alert_issue_timestamp()) {
      set_alert_issue_timestamp(from.alert_issue_timestamp());
    }
    if (from.has_playback_start_timestamp()) {
      set_playback_start_timestamp(from.playback_start_timestamp());
    }
    if (from.has_playback_end_timestamp()) {
      set_playback_end_timestamp(from.playback_end_timestamp());
    }
    if (from.has_playback_success()) {
      set_playback_success(from.playback_success());
    }
    if (from.has_enabled_in_config()) {
      set_enabled_in_config(from.enabled_in_config());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_reason()) {
      set_reason(from.reason());
    }
    if (from.has_latency()) {
      set_latency(from.latency());
    }
    if (from.has_latency_threshold()) {
      set_latency_threshold(from.latency_threshold());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AudioEvent::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AudioEvent::CopyFrom(const AudioEvent& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AudioEvent::IsInitialized() const {

  return true;
}

void AudioEvent::Swap(AudioEvent* other) {
  if (other != this) {
    std::swap(event_code_, other->event_code_);
    std::swap(uuid_, other->uuid_);
    std::swap(frame_timestamp_, other->frame_timestamp_);
    std::swap(alert_issue_timestamp_, other->alert_issue_timestamp_);
    std::swap(playback_start_timestamp_, other->playback_start_timestamp_);
    std::swap(playback_end_timestamp_, other->playback_end_timestamp_);
    std::swap(playback_success_, other->playback_success_);
    std::swap(enabled_in_config_, other->enabled_in_config_);
    std::swap(reason_, other->reason_);
    std::swap(latency_, other->latency_);
    std::swap(latency_threshold_, other->latency_threshold_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AudioEvent::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AudioEvent_descriptor_;
  metadata.reflection = AudioEvent_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int AudioEvents::kEventFieldNumber;
#endif  // !_MSC_VER

AudioEvents::AudioEvents()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:nd_audio.AudioEvents)
}

void AudioEvents::InitAsDefaultInstance() {
}

AudioEvents::AudioEvents(const AudioEvents& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:nd_audio.AudioEvents)
}

void AudioEvents::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AudioEvents::~AudioEvents() {
  // @@protoc_insertion_point(destructor:nd_audio.AudioEvents)
  SharedDtor();
}

void AudioEvents::SharedDtor() {
  if (this != default_instance_) {
  }
}

void AudioEvents::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AudioEvents::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AudioEvents_descriptor_;
}

const AudioEvents& AudioEvents::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_audio_2eproto();
  return *default_instance_;
}

AudioEvents* AudioEvents::default_instance_ = NULL;

AudioEvents* AudioEvents::New() const {
  return new AudioEvents;
}

void AudioEvents::Clear() {
  event_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AudioEvents::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:nd_audio.AudioEvents)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .nd_audio.AudioEvent event = 1;
      case 1: {
        if (tag == 10) {
         parse_event:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_event()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_event;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:nd_audio.AudioEvents)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:nd_audio.AudioEvents)
  return false;
#undef DO_
}

void AudioEvents::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:nd_audio.AudioEvents)
  // repeated .nd_audio.AudioEvent event = 1;
  for (int i = 0; i < this->event_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->event(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:nd_audio.AudioEvents)
}

::google::protobuf::uint8* AudioEvents::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:nd_audio.AudioEvents)
  // repeated .nd_audio.AudioEvent event = 1;
  for (int i = 0; i < this->event_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->event(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nd_audio.AudioEvents)
  return target;
}

int AudioEvents::ByteSize() const {
  int total_size = 0;

  // repeated .nd_audio.AudioEvent event = 1;
  total_size += 1 * this->event_size();
  for (int i = 0; i < this->event_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->event(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AudioEvents::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AudioEvents* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AudioEvents*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AudioEvents::MergeFrom(const AudioEvents& from) {
  GOOGLE_CHECK_NE(&from, this);
  event_.MergeFrom(from.event_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AudioEvents::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AudioEvents::CopyFrom(const AudioEvents& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AudioEvents::IsInitialized() const {

  return true;
}

void AudioEvents::Swap(AudioEvents* other) {
  if (other != this) {
    event_.Swap(&other->event_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AudioEvents::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AudioEvents_descriptor_;
  metadata.reflection = AudioEvents_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace nd_audio

// @@protoc_insertion_point(global_scope)
